# -*- coding: utf-8 -*-
"""Prediksi Harga Saham BBRI Hplus1 Berdasarkan selisih kenaikan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iaNXOACrXkg1BBu2F4kZpTtArW1625Rh

**Import Library & Setup**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import train_test_split
from google.colab import drive

# Mount Drive (Jika belum)
drive.mount('/content/drive')

"""**Data Loading & Feature Engineering (The Fix)**"""

# Load Data
file_path = "/content/drive/MyDrive/FInal Project Celerates Stupen/BBRI.csv"
df = pd.read_csv(file_path)

# Convert Timestamp
df['timestamp'] = pd.to_datetime(df['timestamp'])

print("--- Menyiapkan Fitur Stationary (Selisih/Return) ---")

# 1. Hitung Logaritma Harga (Agar distribusi normal)
df['Open_Log']   = np.log(df['open'])
df['High_Log']   = np.log(df['high'])
df['Low_Log']    = np.log(df['low'])
df['Close_Log']  = np.log(df['close'])
df['Volume_Log'] = np.log(df['volume'] + 1)
df['MA5_Log']    = df['Close_Log'].rolling(5).mean()

# 2. TARGET: Return Besok (Log Harga Besok - Log Harga Hari Ini)
# Kita memprediksi seberapa besar harga akan NAIK/TURUN, bukan angka harganya.
df['Target_Return'] = df['Close_Log'].shift(-1) - df['Close_Log']

# 3. FITUR INPUT (Juga harus berupa selisih/rasio)
# a. Return Harian (Close hari ini - Close kemarin)
df['Feat_Return_1d'] = df['Close_Log'] - df['Close_Log'].shift(1)

# b. Intraday Change (Close - Open)
df['Feat_Close_Open'] = df['Close_Log'] - df['Open_Log']

# c. Volatilitas (High - Low)
df['Feat_High_Low'] = df['High_Log'] - df['Low_Log']

# d. Tren Jangka Pendek (Jarak Close ke MA5)
df['Feat_Dist_MA5'] = df['Close_Log'] - df['MA5_Log']

# e. Perubahan Volume (Volume hari ini - Volume kemarin)
df['Feat_Vol_Change'] = df['Volume_Log'] - df['Volume_Log'].shift(1)

# Hapus NaN akibat shifting
df.dropna(inplace=True)

print(f"Data siap: {len(df)} baris.")
df.head()

"""**Splitting & Scaling**"""

# Definisi Fitur dan Target
features = ['Feat_Return_1d', 'Feat_Close_Open', 'Feat_High_Low',
            'Feat_Dist_MA5', 'Feat_Vol_Change']

X = df[features]
y = df['Target_Return'] # Target kita sekarang adalah Return

# Split Data (80% Train, 20% Test) - Tanpa Shuffle (Time Series)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

# Simpan Log Harga Asli untuk Keperluan Evaluasi (Mengembalikan ke Rupiah)
# Kita butuh harga hari ini untuk menghitung: Harga_Besok = Harga_Hari_Ini * exp(Prediksi_Return)
test_dates = df.loc[X_test.index, 'timestamp']
test_price_today_log = df.loc[X_test.index, 'Close_Log']
test_price_next_actual = np.exp(df.loc[X_test.index, 'Close_Log'].shift(-1)) # Harga Asli Besok (Target Real)

# Scaling (Penting untuk SVR dan Linear Regression)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# Kembalikan ke DataFrame agar nama kolom aman
X_train_scaled = pd.DataFrame(X_train_scaled, columns=features)
X_test_scaled  = pd.DataFrame(X_test_scaled, columns=features)

print("Data berhasil di-split dan di-scaling.")

"""**Training 3 Model (LR, RF, SVR)**"""

models = {}
predictions_return = {} # Menyimpan prediksi dalam bentuk Return

# --- 1. Linear Regression ---
lr = LinearRegression()
lr.fit(X_train_scaled, y_train)
predictions_return['Linear Regression'] = lr.predict(X_test_scaled)
models['Linear Regression'] = lr
print("Linear Regression Selesai.")

# --- 2. Random Forest (Sekarang sudah Optimal!) ---
rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=None,      # Biarkan tumbuh penuh karena fitur sudah bersih
    min_samples_leaf=2,  # Sedikit regularization
    random_state=42
)
rf.fit(X_train, y_train) # RF bisa pakai data non-scaled
predictions_return['Random Forest'] = rf.predict(X_test)
models['Random Forest'] = rf
print("Random Forest Selesai.")

# --- 3. SVR (Support Vector Regression) ---
svr = SVR(kernel='rbf', C=100, gamma=0.1, epsilon=0.001)
svr.fit(X_train_scaled, y_train)
predictions_return['SVR'] = svr.predict(X_test_scaled)
models['SVR'] = svr
print("SVR Selesai.")

"""**Evaluasi & Konversi ke Rupiah**"""

results_rupiah = {}
price_predictions = {} # Menyimpan prediksi harga (Rupiah) untuk plot

print("\n========== HASIL EVALUASI (DALAM RUPIAH) ==========")

for name, pred_return in predictions_return.items():
    # RUMUS REKONSTRUKSI:
    # Log_Harga_Besok = Log_Harga_Hari_Ini + Prediksi_Return
    pred_log_next = test_price_today_log + pred_return

    # Harga_Besok = exp(Log_Harga_Besok)
    pred_price_next = np.exp(pred_log_next)
    price_predictions[name] = pred_price_next

    # Evaluasi dengan Harga Asli Besok (Shifted)
    # Kita harus membuang baris terakhir karena shift(-1) membuat NaN di data asli
    # Tapi karena kita pakai y_test yang sudah selaras, kita pakai y_test index untuk ambil harga asli
    # Cara paling aman: Ambil harga Close asli pada H+1
    actual_price = np.exp(df.loc[X_test.index, 'Close_Log'].shift(-1))

    # Drop NaN terakhir (baris terakhir test set tidak punya 'besok')
    valid_idx = ~np.isnan(actual_price)
    y_true_valid = actual_price[valid_idx]
    y_pred_valid = pred_price_next[valid_idx]

    rmse = np.sqrt(mean_squared_error(y_true_valid, y_pred_valid))
    mae  = mean_absolute_error(y_true_valid, y_pred_valid)
    r2   = r2_score(y_true_valid, y_pred_valid)

    results_rupiah[name] = {'RMSE (Rp)': rmse, 'MAE (Rp)': mae, 'R2 Score': r2}

    print(f"\nModel: {name}")
    print(f"RMSE : Rp {rmse:,.2f}")
    print(f"R2   : {r2:.4f}")

# Tampilkan Tabel Ringkasan
results_df = pd.DataFrame(results_rupiah).T
print("\n--- RINGKASAN PERBANDINGAN ---")
print(results_df.sort_values(by='RMSE (Rp)'))

"""**Visualisasi (200 Hari Terakhir)**"""

last_n = 200
# Ambil data valid saja (buang NaN terakhir)
valid_dates = test_dates[:-1]
valid_actual = np.exp(df.loc[X_test.index[:-1], 'Close_Log'].shift(-1))

plt.figure(figsize=(14, 7))

# Plot Harga Asli
plt.plot(valid_dates[-last_n:], valid_actual[-last_n:],
         label='Harga Asli (Actual)', color='black', linewidth=2)

# Plot Prediksi Model
colors = {'Linear Regression': 'blue', 'Random Forest': 'green', 'SVR': 'red'}
styles = {'Linear Regression': '--', 'Random Forest': '-', 'SVR': ':'}

for name, preds in price_predictions.items():
    # Preds juga harus dipotong 1 terakhir
    plt.plot(valid_dates[-last_n:], preds[:-1][-last_n:],
             label=f'{name}', color=colors[name], linestyle=styles[name], alpha=0.8)

plt.title(f'Prediksi Harga Saham BBRI (Close Price) - {last_n} Hari Terakhir', fontsize=14)
plt.xlabel('Tanggal')
plt.ylabel('Harga (IDR)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""**Manual Input (Mode Penggunaan)**"""

print("\n========== PREDIKSI HARGA BESOK (MANUAL) ==========")
print("Masukkan data pasar hari ini:")

# Input User
open_val  = float(input("Open Hari Ini   : "))
high_val  = float(input("High Hari Ini   : "))
low_val   = float(input("Low Hari Ini    : "))
close_val = float(input("Close Hari Ini  : "))
vol_val   = float(input("Volume Hari Ini : "))

print("\nData Tambahan (Untuk menghitung perubahan):")
prev_close = float(input("Close KEMARIN   : "))
prev_vol   = float(input("Volume KEMARIN  : "))
ma5_val    = float(input("MA 5 Hari       : "))

# --- 1. Hitung Fitur dari Input ---
import math

# Logaritma
log_open  = np.log(open_val)
log_high  = np.log(high_val)
log_low   = np.log(low_val)
log_close = np.log(close_val)
log_vol   = np.log(vol_val + 1)
log_prev_close = np.log(prev_close)
log_prev_vol   = np.log(prev_vol + 1)
log_ma5   = np.log(ma5_val)

# Fitur Selisih (Sesuai Training)
feat_return_1d  = log_close - log_prev_close
feat_close_open = log_close - log_open
feat_high_low   = log_high - log_low
feat_dist_ma5   = log_close - log_ma5
feat_vol_change = log_vol - log_prev_vol

# Buat DataFrame Input
input_df = pd.DataFrame([{
    'Feat_Return_1d': feat_return_1d,
    'Feat_Close_Open': feat_close_open,
    'Feat_High_Low': feat_high_low,
    'Feat_Dist_MA5': feat_dist_ma5,
    'Feat_Vol_Change': feat_vol_change
}])

# --- 2. Scaling (Wajib untuk LR & SVR) ---
input_scaled = scaler.transform(input_df)

# --- 3. Prediksi (Outputnya adalah RETURN) ---
pred_ret_lr  = models['Linear Regression'].predict(input_scaled)[0]
pred_ret_rf  = models['Random Forest'].predict(input_df)[0] # RF pakai data asli
pred_ret_svr = models['SVR'].predict(input_scaled)[0]

# --- 4. Konversi Return ke Harga Rupiah ---
# Harga_Besok = Harga_Hari_Ini * exp(Return)
price_lr  = close_val * np.exp(pred_ret_lr)
price_rf  = close_val * np.exp(pred_ret_rf)
price_svr = close_val * np.exp(pred_ret_svr)

print("\n-------------------------------------------")
print(f"PREDIKSI CLOSE BESOK (Base: {close_val})")
print("-------------------------------------------")
print(f"Linear Regression : Rp {price_lr:,.0f} (Change: {pred_ret_lr*100:.2f}%)")
print(f"Random Forest     : Rp {price_rf:,.0f} (Change: {pred_ret_rf*100:.2f}%)")
print(f"SVR               : Rp {price_svr:,.0f} (Change: {pred_ret_svr*100:.2f}%)")
print("-------------------------------------------")